### PR TITLE
chore(deps): Remove dependency on babel

### PR DESCRIPTION
**Pull request by perrin4869**

### CODE REVIEW

**Comment by theBenForce** [comment]
You'll need to update the PR title to something like `fix: remove dependency on babel` for the auto versioning/release pipeline to work.

**Comment by perrin4869** [comment]
@theBenForce I see, thanks!
In this case I don't want to make a release though, this is only minor refactoring.
I'll try to add some basic tests first, but it's pending a release of https://github.com/serverless/test/pull/140

**Comment by theBenForce** [comment]
You can use the `chore:` prefix for changes that don't require a release and they'll be picked up in the next set of release notes.

Not a big deal though.

**Comment by perrin4869** [comment]
This also removes the usage of `eval` here :)

**Comment by perrin4869** [comment]
Ah just noticed I failed to squash the commits ><;;

**Pull request merged**
